name: Generate Keystore

on:
  workflow_dispatch:
    inputs:
      alias:
        default: grimoire
      password:
        description: 'Придумайте пароль (запомните его!)'
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -alias ${{ github.event.inputs.alias }} \
            -keypass ${{ github.event.inputs.password }} \
            -storepass ${{ github.event.inputs.password }} \
            -keystore grimoire.keystore \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=GrimoireRPG, OU=GrimoireRPG, O=GrimoireRPG, L=Unknown, S=Unknown, C=DE"
        echo "=== Aliases in keystore ==="
          keytool -list -keystore grimoire.keystore -storepass ${{ github.event.inputs.password }}
          echo "=== Base64 ==="
          base64 grimoire.keystore
